version: '3'
services:
  mongo-exercisecheck:
    image: mongo:3.4
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo:/data/db
  exercisecheck:
    build: .
    restart: always
    depends_on:
      - mongo-exercisecheck
    ports:
      - 9000:9000
    environment:
      - NODE_ENV='production'
      - MONGO_URL='mongodb://mongo-exercisecheck:27017/exercisecheck'
